"""
Termite Ransomware Recovery Tool (PoC)
========================================
Decrypts files encrypted by the Termite ransomware family.

File format:
    [0:9]   9-byte magic "Fuck you " (with trailing space, ASCII)
    [9:20]  11-byte per-file header (likely random IV / metadata)
    [20:N]  N-byte ciphertext (XOR with keystream)

Cipher: XOR-based stream cipher. Keystream is generated by an obfuscated
PRNG seeded with a session-specific key (algorithm not yet identified).

USAGE
-----
1. Recover keystream from a known plaintext-ciphertext pair:
       python termite_recovery.py recover-keystream \\
              --plaintext  orig.docx \\
              --ciphertext "orig.docx.Fuck you" \\
              --out keystream.bin

2. Decrypt other files (up to keystream length):
       python termite_recovery.py decrypt \\
              --keystream  keystream.bin \\
              --in         "encrypted.txt.Fuck you" \\
              --out        decrypted.txt

3. Verify a recovered file:
       python termite_recovery.py verify \\
              --decrypted  recovered.txt \\
              --original   original.txt
"""

import argparse
import hashlib
import os
import sys

MAGIC = b"Fuck you "
HEADER_LEN = 11   # per-file header length (after magic, before ciphertext)
TOTAL_OVERHEAD = len(MAGIC) + HEADER_LEN  # = 20 bytes


def recover_keystream(pt_path: str, ct_path: str, out_path: str):
    pt = open(pt_path, "rb").read()
    ct = open(ct_path, "rb").read()

    if not ct.startswith(MAGIC):
        sys.exit(f"[!] {ct_path} does not start with Termite magic 'Fuck you '")

    if len(ct) < TOTAL_OVERHEAD + len(pt):
        sys.exit(f"[!] ciphertext too short: {len(ct)} < {TOTAL_OVERHEAD + len(pt)}")

    # Extract per-file header (informational)
    per_file_hdr = ct[len(MAGIC):TOTAL_OVERHEAD]
    print(f"[*] Per-file header (bytes 9..20): {per_file_hdr.hex()}")

    body = ct[TOTAL_OVERHEAD:]
    n = min(len(pt), len(body))
    keystream = bytes(pt[i] ^ body[i] for i in range(n))

    with open(out_path, "wb") as f:
        f.write(keystream)
    print(f"[+] Recovered {len(keystream)} bytes of keystream -> {out_path}")
    print(f"    First 32 bytes: {keystream[:32].hex()}")
    return keystream


def decrypt_file(ct_path: str, ks_path: str, out_path: str):
    ct = open(ct_path, "rb").read()
    keystream = open(ks_path, "rb").read()

    if not ct.startswith(MAGIC):
        sys.exit(f"[!] {ct_path} does not start with Termite magic 'Fuck you '")

    body = ct[TOTAL_OVERHEAD:]
    if len(body) > len(keystream):
        print(f"[!] WARN: ciphertext body ({len(body)} B) > keystream "
              f"({len(keystream)} B). Only first {len(keystream)} B decryptable.")

    n = min(len(body), len(keystream))
    pt = bytes(body[i] ^ keystream[i] for i in range(n))

    with open(out_path, "wb") as f:
        f.write(pt)
    print(f"[+] Decrypted {n} bytes -> {out_path}")
    return pt


def verify_decryption(decrypted_path: str, original_path: str):
    decrypted = open(decrypted_path, "rb").read()
    original = open(original_path, "rb").read()

    md5_d = hashlib.md5(decrypted).hexdigest()
    md5_o = hashlib.md5(original).hexdigest()

    n = min(len(decrypted), len(original))
    matches = sum(1 for i in range(n) if decrypted[i] == original[i])
    pct = 100.0 * matches / n if n else 0

    print(f"\n=== VERIFICATION ===")
    print(f"  decrypted: {len(decrypted)} bytes  (MD5 {md5_d})")
    print(f"  original:  {len(original)} bytes  (MD5 {md5_o})")
    print(f"  byte-match: {matches}/{n} ({pct:.2f}%)")
    if md5_d == md5_o and len(decrypted) == len(original):
        print(f"  >>> PERFECT MATCH - recovery confirmed <<<")
        return True
    return False


def main():
    p = argparse.ArgumentParser(description="Termite ransomware recovery PoC")
    sub = p.add_subparsers(dest="cmd", required=True)

    r = sub.add_parser("recover-keystream", help="Recover keystream from PT/CT pair")
    r.add_argument("--plaintext", required=True)
    r.add_argument("--ciphertext", required=True)
    r.add_argument("--out", required=True)

    d = sub.add_parser("decrypt", help="Decrypt a file using a keystream")
    d.add_argument("--keystream", required=True)
    d.add_argument("--in", dest="in_path", required=True)
    d.add_argument("--out", required=True)

    v = sub.add_parser("verify", help="Verify a decrypted file vs original")
    v.add_argument("--decrypted", required=True)
    v.add_argument("--original", required=True)

    args = p.parse_args()
    if args.cmd == "recover-keystream":
        recover_keystream(args.plaintext, args.ciphertext, args.out)
    elif args.cmd == "decrypt":
        decrypt_file(args.in_path, args.keystream, args.out)
    elif args.cmd == "verify":
        verify_decryption(args.decrypted, args.original)


if __name__ == "__main__":
    main()
